/**
 * Agent Skill auto-extraction (Hermes pattern, Anchor-fitted).
 *
 * Idea: after every successful execute_code run, log the code's "signature"
 * (sorted set of anchor.X.Y calls). When the same signature succeeds 3+ times
 * for the same agent, crystallize it into a named skill. Next time that agent
 * runs, its system prompt lists the extracted skills — the LLM sees "you have
 * a proven pattern called weekly_digest" and re-emits similar code without
 * needing to redesign the approach.
 *
 * This is the COMPOUNDING loop: more use → more skills → better next run.
 *
 * Design choices:
 *   • Per-agent skills (not global) — each user_agents row has its own library
 *   • Signature = API call set only (params ignored) — clusters same-shape code
 *   • Threshold 3 successes — fast enough to feel useful, slow enough to filter
 *     one-offs
 *   • Name/description generated by cheap LLM once at crystallization — cached
 *     forever in DB
 *   • Skills surface via system prompt, NOT as a callable RPC — LLM chooses
 *     how to reuse (copy code, adapt, ignore). Simpler than a skill runtime.
 */
import crypto from "crypto";
import { nanoid } from "nanoid";
import { db } from "../infra/storage/db.js";
import { text as llmText } from "../infra/compute/index.js";

const CRYSTALLIZE_THRESHOLD = 3;

/** Extract anchor.X.Y( call patterns from a code block, sort+hash. */
export function computeSignature(code: string): { hash: string; calls: string[] } {
  const matches = code.match(/anchor\.([a-z_][a-z_0-9]*\.[a-z_][a-z_0-9]*)\s*\(/gi) ?? [];
  const calls = Array.from(new Set(
    matches.map((m) => m.replace(/\s*\(.*$/, "").replace(/^anchor\./, "").toLowerCase())
  )).sort();
  const hash = crypto.createHash("sha256").update(calls.join("|")).digest("hex").slice(0, 16);
  return { hash, calls };
}

/** Called after a successful execute_code run. Logs candidate, maybe crystallizes. */
export async function recordSuccessfulRun(opts: {
  agentId: string;
  agentName: string;
  lang: string;
  code: string;
  runId: string;
}): Promise<void> {
  const { hash, calls } = computeSignature(opts.code);
  if (calls.length < 2) return; // single-call runs aren't worth tracking

  // Record candidate
  db.prepare(
    "INSERT INTO agent_skill_candidates (id, agent_id, signature, code, lang, run_id) VALUES (?,?,?,?,?,?)"
  ).run(nanoid(), opts.agentId, hash, opts.code, opts.lang, opts.runId);

  // Already crystallized? bump success_count
  const existing = db.prepare(
    "SELECT id, success_count FROM agent_skills WHERE agent_id=? AND signature=?"
  ).get(opts.agentId, hash) as any;

  if (existing) {
    db.prepare(
      "UPDATE agent_skills SET success_count=success_count+1, last_used_at=datetime('now') WHERE id=?"
    ).run(existing.id);
    return;
  }

  // Not yet a skill — count candidates for this signature
  const count = (db.prepare(
    "SELECT COUNT(*) as c FROM agent_skill_candidates WHERE agent_id=? AND signature=?"
  ).get(opts.agentId, hash) as any).c as number;

  if (count < CRYSTALLIZE_THRESHOLD) return;

  // Crystallize — async LLM name/description generation (fire and forget).
  crystallize({
    agentId: opts.agentId,
    agentName: opts.agentName,
    lang: opts.lang,
    signature: hash,
    calls,
    latestCode: opts.code,
    runId: opts.runId,
  }).catch((err) => {
    console.error(`[SkillExtractor] crystallize failed for ${opts.agentId}:`, err.message);
  });
}

async function crystallize(opts: {
  agentId: string;
  agentName: string;
  lang: string;
  signature: string;
  calls: string[];
  latestCode: string;
  runId: string;
}): Promise<void> {
  // Re-check — another concurrent run may have crystallized already
  const existing = db.prepare(
    "SELECT id FROM agent_skills WHERE agent_id=? AND signature=?"
  ).get(opts.agentId, opts.signature);
  if (existing) return;

  // Ask LLM for a short name + description based on the code pattern
  const system = `You name reusable code patterns. Output ONLY valid JSON {"name": "...", "description": "..."} with:
- name: snake_case, 2-4 words, describes what the pattern does
- description: one sentence, 20 words max, plain language

The code uses these anchor APIs: ${opts.calls.join(", ")}.`;

  const user = `Name this pattern:\n\n\`\`\`${opts.lang}\n${opts.latestCode.slice(0, 2000)}\n\`\`\``;

  let name = `skill_${opts.signature}`;
  let description = `Reusable pattern using ${opts.calls.slice(0, 3).join(", ")}`;

  try {
    const raw = await llmText({
      task: "twin_edit_learning",
      system,
      messages: [{ role: "user", content: user }],
      maxTokens: 200,
      runId: opts.runId,
      agentName: `SkillExtractor (${opts.agentName})`,
    });
    const json = JSON.parse(raw.match(/\{[\s\S]*\}/)?.[0] ?? "{}");
    if (typeof json.name === "string" && json.name.trim()) {
      name = json.name.trim().replace(/[^a-z_0-9]/gi, "_").toLowerCase().slice(0, 40);
    }
    if (typeof json.description === "string" && json.description.trim()) {
      description = json.description.trim().slice(0, 200);
    }
  } catch (err: any) {
    // Keep fallback name/description on parse/LLM failure
  }

  try {
    db.prepare(
      "INSERT INTO agent_skills (id, agent_id, name, description, signature, template, lang, success_count, last_used_at) VALUES (?,?,?,?,?,?,?,?,datetime('now'))"
    ).run(
      nanoid(), opts.agentId, name, description, opts.signature,
      opts.latestCode.slice(0, 8000), opts.lang, CRYSTALLIZE_THRESHOLD
    );
    console.log(`[SkillExtractor] Crystallized: ${opts.agentName} / ${name} (sig ${opts.signature}, uses ${opts.calls.length} APIs)`);
  } catch {
    // Race — another process crystallized first. Fine.
  }
}

/** Read an agent's crystallized skills for system prompt injection. */
export function listSkillsForAgent(agentId: string, limit = 10): Array<{
  name: string; description: string; lang: string; template: string; successCount: number;
}> {
  const rows = db.prepare(
    "SELECT name, description, lang, template, success_count as successCount FROM agent_skills WHERE agent_id=? ORDER BY success_count DESC, last_used_at DESC LIMIT ?"
  ).all(agentId, limit) as any[];
  return rows;
}

/** Render skills list as a compact system-prompt addendum. */
export function renderSkillsForPrompt(agentId: string): string {
  const skills = listSkillsForAgent(agentId, 8);
  if (skills.length === 0) return "";
  const lines = skills.map((s, i) =>
    `${i + 1}. **${s.name}** — ${s.description} (${s.successCount}× successful, ${s.lang})`
  );
  return `\n\n──── YOUR PROVEN PATTERNS ────\nYou've run these patterns successfully before. For similar tasks, reuse the same approach:\n\n${lines.join("\n")}\n\nWhen a task matches one of these, write code following the same structure — you know it works.\n────`;
}
